name: Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set Proxy
      run: |
        export HTTP_PROXY=http://192.168.43.117:8080
        export HTTPS_PROXY=http://192.168.43.117:8080
        export http_proxy=http://192.168.43.117:8080
        export https_proxy=http://192.168.43.117:8080
        --verbose

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3 python3-pip build-essential git zip unzip openjdk-11-jdk wget
        pip install --upgrade pip
        pip install buildozer cython

    - name: Install Android SDK and NDK
      run: |
        sudo apt install -y wget
        wget https://dl.google.com/android/repository/commandlinetools-linux-8092744_latest.zip
        mkdir -p $HOME/android-sdk
        unzip commandlinetools-linux-8092744_latest.zip -d $HOME/android-sdk/cmdline-tools
        mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/tools
        export ANDROID_HOME=$HOME/android-sdk
        export PATH=$ANDROID_HOME/cmdline-tools/tools/bin:$ANDROID_HOME/platform-tools:$PATH
        sdkmanager --install "build-tools;33.0.2" "platforms;android-33" "platform-tools" "ndk;23.1.7779620" "aidl" --accept-licenses
        echo y | sdkmanager --licenses  # "yes" o'rniga "echo y" ishlatish

    - name: Build APK
      run: |
        export ANDROID_HOME=$HOME/android-sdk
        export PATH=$ANDROID_HOME/cmdline-tools/tools/bin:$ANDROID_HOME/platform-tools:$PATH
        buildozer -v android debug --verbose  # Verbose rejimni qo'shdik

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: CounterApp-debug.apk
        path: bin/*.apk
